name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 18 * * 6" # Saturdays at 12pm CST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3", "3.4", "4.0"]
        rails-version-env:
          - RAILS_VERSION="~> 7.2.0"
          - RAILS_VERSION="~> 8.0.0"
          - RAILS_VERSION="~> 8.1.0"
        allow-failure: [false]
        include:
          - ruby-version: "ruby-head"
            rails-version-env: RAILS_VERSION="~> 8.1.0"
            allow-failure: true
          - ruby-version: "4.0"
            rails-version-env: RAILS_BRANCH="main"
            allow-failure: true
          - ruby-version: "4.0"
            rails-version-env: RAILS_BRANCH="8-1-stable"
            allow-failure: true
          - ruby-version: "4.0"
            rails-version-env: RAILS_BRANCH="8-0-stable"
            allow-failure: true
          - ruby-version: "4.0"
            rails-version-env: RAILS_BRANCH="7-2-stable"
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Update bundle
        run: ${{ matrix.rails-version-env }} bundle update
      - name: Run tests
        run: ${{ matrix.rails-version-env }} bundle exec rake
